name: PHP Lint
on: [push]
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP Lint
        run: find . -name '*.php' -print0 | xargs -0 -n 1 php -l
